CREATE IF NOT EXISTS TABLE CDC_REPORTED_PATIENT_IMPACT_TIMESERIES (
	STATE VARCHAR(2),
	CRITICAL_STAFFING_SHORTAGE_TODAY_YES NUMBER(38,0),
	CRITICAL_STAFFING_SHORTAGE_TODAY_NO NUMBER(38,0),
	CRITICAL_STAFFING_SHORTAGE_TODAY_NOT_REPORTED NUMBER(38,0),
	CRITICAL_STAFFING_SHORTAGE_ANTICIPATED_WITHIN_WEEK_YES NUMBER(38,0),
	CRITICAL_STAFFING_SHORTAGE_ANTICIPATED_WITHIN_WEEK_NO NUMBER(38,0),
	CRITICAL_STAFFING_SHORTAGE_ANTICIPATED_WITHIN_WEEK_NOT_REPORTED NUMBER(38,0),
	HOSPITAL_ONSET_COVID NUMBER(38,0),
	HOSPITAL_ONSET_COVID_COVERAGE NUMBER(38,0),
	INPATIENT_BEDS NUMBER(38,0),
	INPATIENT_BEDS_COVERAGE NUMBER(38,0),
	INPATIENT_BEDS_USED NUMBER(38,0),
	INPATIENT_BEDS_USED_COVERAGE NUMBER(38,0),
	INPATIENT_BEDS_USED_COVID NUMBER(38,0),
	INPATIENT_BEDS_USED_COVID_COVERAGE NUMBER(38,0),
	PREVIOUS_DAY_ADMISSION_ADULT_COVID_CONFIRMED NUMBER(38,0),
	PREVIOUS_DAY_ADMISSION_ADULT_COVID_CONFIRMED_COVERAGE NUMBER(38,0),
	PREVIOUS_DAY_ADMISSION_ADULT_COVID_SUSPECTED NUMBER(38,0),
	PREVIOUS_DAY_ADMISSION_ADULT_COVID_SUSPECTED_COVERAGE NUMBER(38,0),
	PREVIOUS_DAY_ADMISSION_PEDIATRIC_COVID_CONFIRMED NUMBER(38,0),
	PREVIOUS_DAY_ADMISSION_PEDIATRIC_COVID_CONFIRMED_COVERAGE NUMBER(38,0),
	PREVIOUS_DAY_ADMISSION_PEDIATRIC_COVID_SUSPECTED NUMBER(38,0),
	PREVIOUS_DAY_ADMISSION_PEDIATRIC_COVID_SUSPECTED_COVERAGE NUMBER(38,0),
	STAFFED_ADULT_ICU_BED_OCCUPANCY NUMBER(38,0),
	STAFFED_ADULT_ICU_BED_OCCUPANCY_COVERAGE NUMBER(38,0),
	STAFFED_ICU_ADULT_PATIENTS_CONFIRMED_AND_SUSPECTED_COVID NUMBER(38,0),
	STAFFED_ICU_ADULT_PATIENTS_CONFIRMED_AND_SUSPECTED_COVID_COVERAGE NUMBER(38,0),
	STAFFED_ICU_ADULT_PATIENTS_CONFIRMED_COVID NUMBER(38,0),
	STAFFED_ICU_ADULT_PATIENTS_CONFIRMED_COVID_COVERAGE NUMBER(38,0),
	TOTAL_ADULT_PATIENTS_HOSPITALIZED_CONFIRMED_AND_SUSPECTED_COVID NUMBER(38,0),
	TOTAL_ADULT_PATIENTS_HOSPITALIZED_CONFIRMED_AND_SUSPECTED_COVID_COVERAGE NUMBER(38,0),
	TOTAL_ADULT_PATIENTS_HOSPITALIZED_CONFIRMED_COVID NUMBER(38,0),
	TOTAL_ADULT_PATIENTS_HOSPITALIZED_CONFIRMED_COVID_COVERAGE NUMBER(38,0),
	TOTAL_PEDIATRIC_PATIENTS_HOSPITALIZED_CONFIRMED_AND_SUSPECTED_COVID NUMBER(38,0),
	TOTAL_PEDIATRIC_PATIENTS_HOSPITALIZED_CONFIRMED_AND_SUSPECTED_COVID_COVERAGE NUMBER(38,0),
	TOTAL_PEDIATRIC_PATIENTS_HOSPITALIZED_CONFIRMED_COVID NUMBER(38,0),
	TOTAL_PEDIATRIC_PATIENTS_HOSPITALIZED_CONFIRMED_COVID_COVERAGE NUMBER(38,0),
	TOTAL_STAFFED_ADULT_ICU_BEDS NUMBER(38,0),
	TOTAL_STAFFED_ADULT_ICU_BEDS_COVERAGE NUMBER(38,0),
	INPATIENT_BEDS_UTILIZATION FLOAT,
	INPATIENT_BEDS_UTILIZATION_COVERAGE NUMBER(38,0),
	INPATIENT_BEDS_UTILIZATION_NUMERATOR NUMBER(38,0),
	INPATIENT_BEDS_UTILIZATION_DENOMINATOR NUMBER(38,0),
	PERCENT_OF_INPATIENTS_WITH_COVID FLOAT,
	PERCENT_OF_INPATIENTS_WITH_COVID_COVERAGE NUMBER(38,0),
	PERCENT_OF_INPATIENTS_WITH_COVID_NUMERATOR NUMBER(38,0),
	PERCENT_OF_INPATIENTS_WITH_COVID_DENOMINATOR NUMBER(38,0),
	INPATIENT_BED_COVID_UTILIZATION FLOAT,
	INPATIENT_BED_COVID_UTILIZATION_COVERAGE NUMBER(38,0),
	INPATIENT_BED_COVID_UTILIZATION_NUMERATOR NUMBER(38,0),
	INPATIENT_BED_COVID_UTILIZATION_DENOMINATOR NUMBER(38,0),
	ADULT_ICU_BED_COVID_UTILIZATION FLOAT,
	ADULT_ICU_BED_COVID_UTILIZATION_COVERAGE NUMBER(38,0),
	ADULT_ICU_BED_COVID_UTILIZATION_NUMERATOR NUMBER(38,0),
	ADULT_ICU_BED_COVID_UTILIZATION_DENOMINATOR NUMBER(38,0),
	ADULT_ICU_BED_UTILIZATION FLOAT,
	ADULT_ICU_BED_UTILIZATION_COVERAGE NUMBER(38,0),
	ADULT_ICU_BED_UTILIZATION_NUMERATOR NUMBER(38,0),
	ADULT_ICU_BED_UTILIZATION_DENOMINATOR NUMBER(38,0),
	REPORTING_CUTOFF_START TIMESTAMP_NTZ(9),
	ISO3166_1 VARCHAR(2),
	ISO3166_2 VARCHAR(2),
	LAST_UPDATE_DATE TIMESTAMP_NTZ(9),
	LAST_REPORTED_FLAG BOOLEAN
);

INSERT INTO CDC_REPORTED_PATIENT_IMPACT_TIMESERIES
SELECT * 
FROM CDC_REPORTED_PATIENT_IMPACT c
WHERE c.REPORTING_CUTOFF_START > (
  SELECT NVL(MAX(REPORTING_CUTOFF_START), '1900-01-01')
  FROM CDC_REPORTED_PATIENT_IMPACT_TIMESERIES
);

UPDATE CDC_REPORTED_PATIENT_IMPACT_TIMESERIES
SET LAST_REPORTED_FLAG = REPORTING_CUTOFF_START = (
  WITH last_run AS (
    SELECT MAX(REPORTING_CUTOFF_START) as val
    FROM CDC_REPORTED_PATIENT_IMPACT_TIMESERIES
  )
  SELECT val FROM last_run
);
